package Chimpy;

import Chimpy.texto.Lector;
import Chimpy.texto.Marcador;
import Chimpy.texto.Traductor;
import java.awt.Color;
import java.awt.Font;
import javax.swing.ImageIcon;



public class Hoja extends javax.swing.JFrame {
    
    public Hoja() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        setIconImage(new ImageIcon(getClass().getResource("/Recursos/images/logo.png")).getImage());
        panel.setBackground(Color.decode("#1E1E1E"));
        texto.setFont(new Font("JetBrains Mono", Font.PLAIN, 16));
        texto.setForeground(Color.decode("#D4D4D4"));
        texto.setBackground(Color.decode("#1E1E1E"));
        texto.setCaretColor(Color.WHITE);
        texto1.setFont(new Font("JetBrains Mono", Font.PLAIN, 16));
        texto1.setForeground(Color.decode("#D4D4D4"));
        texto1.setBackground(Color.decode("#1E1E1E"));
        texto1.setCaretColor(Color.WHITE);
        new Marcador().colors(texto);
        new Marcador().colors(texto1);
        traductor.addActionListener(e->{ new Traductor().traducirJava(texto); new Lector().abrirArchivo(texto1, this);});
        //traductor1.addActionListener(e->{ new Traductor().traducirChimpy(texto1); new Lector().abrirArchivoJava(texto, this);});
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        traductor = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextPane();
        scrollPane1 = new javax.swing.JScrollPane();
        texto1 = new javax.swing.JTextPane();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        traductor.setBackground(new java.awt.Color(70, 70, 70));
        traductor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        traductor.setForeground(new java.awt.Color(220, 220, 220));
        traductor.setText("traducir a Java");
        panel.add(traductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, -1));

        texto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        scrollPane.setViewportView(texto);

        panel.add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 360, 410));

        texto1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        scrollPane1.setViewportView(texto1);

        panel.add(scrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 360, 410));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Ejecutar código");
        panel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hoja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hoja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel panel;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JScrollPane scrollPane1;
    private javax.swing.JTextPane texto;
    private javax.swing.JTextPane texto1;
    private javax.swing.JButton traductor;
    // End of variables declaration//GEN-END:variables
}
